Fix get_accel_from_plan unpacking for v0.10.1
In v0.10.1, get_accel_from_plan returns 3 values (v_target, a_target,
should_stop) instead of 2. Update unpacking to handle all return values.

Error fixed:
ValueError: too many values to unpack (expected 2)

Solution:
Changed from:
  output_a_target_mpc, output_should_stop_mpc = get_accel_from_plan(...)

To:
  output_v_target_mpc, output_a_target_mpc, output_should_stop_mpc = get_accel_from_plan(...)